[package]
authors = ["Pouya M. B. <pooyamb@gmail.com>"]
edition = "2018"
name = "fibonacci"
version = "0.1.0"

[dependencies]
basteh = "0.4.0-alpha.3"
basteh-memory = "0.4.0-alpha.3"
actix-web = "4.0.0"

[[example]]
name = "fibonacci"
path = "./src/app.rs"
